let value = prompt(
    "Ingrese uno de los siguientes departamentos: \n  Cundinamarca\n  Quindio\n  Antioquia\n  Valle"
  );
let value2 = prompt(
    "Ingrese la actividad deseada: \n  Turismo\n  Comidas\n  Museos"
  );
if (value === null || value === "") {
    alert ("*** Departamento Inválido ***")
} else if (value2 === null || value2 === "") {
    alert("*** Actividad Inválida ***")
} else {
    value = value.toLowerCase();
    value2 = value2.toLowerCase();
    if (value === "cundinamarca" && value2 === "turismo") {
        alert("Cundinamarca, Colombia, ofrece diversas atracciones:\n\n Adéntrate en la Catedral de Sal en Zipaquirá.\n Descubre Guatavita y su mítica Laguna.\n Disfruta del encanto colonial de Villa de Leyva.\n Aventúrate en Chicaque para senderismo y naturaleza.\n Visita La Chorrera, la cascada más alta del país.\n Explora minas de sal en Nemocon y Nemocon.\n Encuentra cerámica única en Ráquira.\n Diviértete en el Parque Jaime Duque, temático.\n Escalada y montañismo en Suesca para los más aventureros.")
    } else if (value === "cundinamarca" && value2 === "comidas") {
        alert("Comidas típicas de Cundinamarca, Colombia:\n\n Ajiaco: Sopa de pollo y papas con guascas.\n Fritanga: Carnes fritas y embutidos variados.\n Tamales cundiboyacenses: Maíz relleno de carne y vegetales.\n Arepas boyacenses: Maíz amarillo relleno de queso.\n Trucha: Pescado popular de la región.\n Mazamorra chiquita: Postre de maíz morado y panela.\n Almojábanas y pandebonos: Panecillos de queso horneados.\n Puchero: Guiso de carne, maíz y plátano.\n Caldo de papa: Sopa de papas con huevo y alcaparras.\n Changua: Sopa de leche con huevo, cebolla y cilantro.")
    } else if (value === "cundinamarca" && value2 === "museos") {
        alert("Cundinamarca alberga varios museos destacados que reflejan su historia y cultura:\n\n Museo del Oro: Bogotá, colección de artefactos precolombinos y orfebrería.\n Museo Botero: Bogotá, obras de Fernando Botero y otros artistas.\n Museo Nacional: Bogotá, historia de Colombia a través de arte y objetos.\n Museo de Arte Moderno de Bogotá: Obras de artistas colombianos y extranjeros.\n Museo Arqueológico de Suesca: Piezas arqueológicas de la región.\n Museo El Dorado: Colección de arte precolombino en Bogotá.\n Museo de la Independencia: Casa del florero en Bogotá, eventos históricos.\n Museo de Sal de Nemocon: Historia minera y geológica.\n Museo de Historia Natural de la Salle: Exhibe biodiversidad y fósiles.\n Museo Villa de Leyva: Arte religioso y colonial en el pueblo homónimo.")
    } else if ((value === "quindio" || value === "quindío") && value2 === "turismo") {
        alert("El Quindío, Colombia, ofrece encanto natural y cultural:\n\n Eje Cafetero: Región cafetalera con hermosos paisajes y fincas.\n Salento: Pueblo pintoresco, Calle Real, Valle de Cocora.\n Parque del Café: Parque temático y acuático dedicado al café.\n Jardín Botánico del Quindío: Biodiversidad y senderos.\n Recuca: Experiencia de vivir como campesino cafetero.\n Armenia: Capital, catedral, museos y vida urbana.\n Parque Panaca: Parque temático agropecuario e interactivo.\n Filandia: Arquitectura tradicional y miradores.\n Termales de Santa Rosa de Cabal: Aguas termales y cascadas.\n Pijao: Pueblo tranquilo con historia y cultura cafetera.")
    } else if ((value === "quindio" || value === "quindío") && value2 === "comidas") {
        alert("La gastronomía del Quindío, Colombia, ofrece sabores únicos:\n\n Bandeja Paisa: Plato abundante con carne, arroz, frijoles, plátano, huevo y más.\n Arepas de Chócolo: Arepas de maíz tierno con queso.\n Mazamorra de ñame: Postre dulce de ñame con panela y canela.\n Tamal Tolimense: Tamal relleno de carne, arvejas y arroz.\n Chorizo Quindiano: Embutido regional condimentado y delicioso.\n Aguapanela con queso: Bebida de panela con queso fresco.\n Trucha a la Parrilla: Pescado fresco asado con guarniciones.\n Patacón: Plátano verde frito y aplastado, acompañamiento típico.\n Cuy Asado: Preparación de cuy (roedor) al horno.\n Arequipe: Dulce de leche caramelizado, común en postres.")
    } else if ((value === "quindio" || value === "quindío") && value2 === "museos") {
        alert("El Quindío, Colombia, cuenta con museos que resaltan su cultura y pasado:\n\n Museo del Oro Quimbaya: Arte precolombino y orfebrería indígena.\n Museo de Arte de Quindío: Exhibiciones de artistas locales y nacionales.\n Museo Rayo: Arte contemporáneo y obras del maestro Omar Rayo.\n Museo de la Cultura Ancestral Quimbaya: Historia de la etnia Quimbaya.\n Museo de la Realidad del Quindío: Cultura y tradiciones de la región.\n Museo del Carriel: Exhibe accesorios de la indumentaria típica.\n Museo de la Caña de Azúcar: Historia de la producción de caña.\n Museo del Bambú y Guadua: Muestra la versatilidad de estos materiales.\n Museo Arqueológico de Filandia: Artefactos indígenas y coloniales.\n Museo Etnográfico Quimbaya: Arte y objetos de las culturas indígenas locales.")
    } else if (value === "antioquia" && value2 === "turismo") {
        alert("Antioquia, Colombia, ofrece un turismo diverso y vibrante:\n\n Medellín: Ciudad moderna, Metrocable, Parque Explora.\n Guatapé: Coloridos zócalos, Piedra del Peñol, embalse.\n Santa Fe de Antioquia: Arquitectura colonial, puentes y calles adoquinadas.\n Parque Arví: Naturaleza y senderismo cerca de Medellín.\n Jardín: Pueblo tradicional, Paisaje Cultural Cafetero.\n Parque Nacional Natural Los Nevados: Trekking y paisajes montañosos.\n Santuario de las Lajas: Santuario religioso en Ipiales.\n Jericó: Encanto religioso, iglesia y cultura cafetera.\n Pueblito Paisa: Réplica de un pueblo antioqueño en Medellín.\n Feria de las Flores: Evento anual con desfiles y festivales en Medellín.")
    } else if (value === "antioquia" && value2 === "comidas") {
        alert("La gastronomía de Antioquia, Colombia, es rica y sabrosa:\n\n Bandeja Paisa: Plato icónico con carne, arroz, frijoles, plátano, huevo y chicharrón.\n Sancocho Antioqueño: Sopa abundante con carne, maíz, papa y plátano.\n Arepas Paisas: Arepas de maíz con queso y chicharrón.\n Mazamorra Antioqueña: Postre de maíz morado con leche y panela.\n Bollo Antioqueño: Masa de maíz rellena de carne o queso.\n Chorizo Antioqueño: Embutido condimentado, ideal en parrilladas.\n Chicharrón: Carne de cerdo frita y crujiente, acompañamiento popular.\n Hormigas Culonas: Delicadeza culinaria, fritas y sazonadas.\n Arepuelas: Pequeñas arepas dulces fritas, con anís y azúcar.\n Envueltos Antioqueños: Hojas de plátano rellenas de maíz y carne, cocidas al vapor.")
    } else if (value === "antioquia" && value2 === "museos") {
        alert("En Antioquia, Colombia, encuentras museos que reflejan su historia y cultura:\n\n Museo de Antioquia: Obras de Fernando Botero y arte colombiano.\n Museo de Arte Moderno de Medellín: Arte contemporáneo local e internacional.\n Museo El Castillo: Mansiones históricas y arte en Medellín.\n Museo de Arte Universidad de Antioquia: Obras de maestros colombianos.\n Museo de Arte de la Secretaría de Educación: Arte y cultura en Medellín.\n Museo Cementerio San Pedro: Historia y arte funerario.\n Museo Casa de la Memoria: Conmemora el conflicto y busca la reconciliación.\n Museo del Agua EPM: Educación sobre el recurso hídrico.\n Museo Casa Gardeliana: Rinde homenaje al tango y a Carlos Gardel.\n Museo Entomológico Piedras Blancas: Exhibe la biodiversidad de insectos.")
    } else if (value === "valle" && value2 === "turismo") {
        alert("El Valle del Cauca, Colombia, ofrece una variada oferta turística:\n\n Cali: Salsa, vida nocturna y monumentos históricos.\n Zoológico de Cali: Amplia colección de animales.\n Cristo Rey: Monumento religioso con vistas panorámicas.\n Buga: Basílica del Señor de los Milagros y arquitectura colonial.\n Lago Calima: Deporte acuático y naturaleza en la región del Pacífico.\n Parque Nacional Natural Farallones de Cali: Senderismo y biodiversidad.\n Salud y Vida: Termales y balnearios en Santa Rosa de Cabal.\n Darién: Playas vírgenes y ecoturismo en la costa del Pacífico.\n Jardín Botánico Juan María Céspedes: Flora y fauna regional en Cali.\n Feria de Cali: Evento anual con música, danza y diversión.")
    } else if (value === "valle" && value2 === "comidas") {
        alert("La gastronomía del Valle del Cauca, Colombia, presenta sabores auténticos:\n\n Sancocho de Gallina: Sopa abundante con gallina, plátano y yuca.\n Arroz Atollado: Arroz con pollo, cerdo y verduras, cocido con caldo.\n Champus: Bebida tradicional a base de maíz, panela y lulo.\n Empanadas Vallunas: Empanadas rellenas de carne y papa, fritas.\n Cazuela de Mariscos: Guiso de mariscos con arroz y plátano.\n Ajiaco de Cuy: Sopa de cuy (roedor) con papas y maíz.\n Chorizo Valluno: Embutido sazonado y ahumado.\n Bocadillo de Guayaba: Dulce de guayaba tradicional.\n Almojábana: Panecillo de queso horneado, popular en desayunos.\n Dulce de Mango Biche: Mango verde en almíbar, postre típico.")
    } else if (value === "valle" && value2 === "museos") {
        alert("El Valle del Cauca, Colombia, cuenta con museos que resaltan su historia y cultura:\n\n Museo La Tertulia: Arte contemporáneo y exhibiciones culturales en Cali.\n Museo Arqueológico La Merced: Piezas prehispánicas y religiosas en Cali.\n Museo de Oro Calima: Arte precolombino y orfebrería en Calima Darién.\n Museo de Arte Moderno La Tertulia: Obras de arte moderno y contemporáneo.\n Museo de la Caña de Azúcar: Historia de la industria azucarera.\n Museo Rayo: Obras del maestro Omar Rayo en Roldanillo.\n Museo Aéreo Fénix: Aviones y objetos históricos de la aviación.\n Museo Farallones de Cali: Biodiversidad y conservación en los Andes.\n Museo Carlos Sarmiento Lora: Arte, historia y cultura en Buga.\n Museo de Arte Religioso de la Catedral de Santiago de Cali: Reliquias y objetos religiosos en la catedral.")
    } else {
        alert(value +" ó "+ value2 + " no es una consulta válida")
    }
}